name: 7amadas for 7amadas

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 


jobs:
  Greetings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Greet
        run: echo "Welcome 7amada from 7amada"
        shell: bash
      
